version: 2

project_name: go-support

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/adamrobbie/go-support/pkg/appid.AppVersion={{.Version}}
    main: ./main.go
    binary: go-support

archives:
  - id: default
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE
      - .env.example
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

# Use default snapshot settings
snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

release:
  github:
    owner: adamrobbie
    name: go-support
  draft: true
  prerelease: auto
  name_template: "v{{.Version}}" 